version: '5'

services:
    cat_legalhub:
        # two ways to enable puppeteer:
        # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
        # * (consumes more disk space and memory) leave everything unchanged
        image: legalgeek/cat:1.1
        restart: always
        ports:
            - '1400:1200'
        environment:
            TZ: Asia/Shanghai
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'  # marked
            CACHE_EXPIRE: 6000
            CACHE_CONTENT_EXPIRE: 86400
        depends_on:
            - redis
            - browserless  # marked

    browserless:  # marked
        image: browserless/chrome  # marked
        restart: always  # marked
        environment:
            TZ: Asia/Shanghai
        ulimits:  # marked
          core:  # marked
            hard: 0  # marked
            soft: 0  # marked

    redis:
        image: redis:alpine
        restart: always
        environment:
            TZ: Asia/Shanghai
        volumes:
            - redis-data:/data

volumes:
    redis-data:


